### ISSUE TITLE
French data

### ISSUE THREAD

**Issue by patricoferris** [geocaml/carbon-intensity#6]
@maiste suggested looking at https://data.rte-france.com/ for data from France.

**Comment by emillon** [comment]
I managed to get the data from the `eco2mix-national-tr` dataset. Here's a python sample that displays the latest value:

```py
import requests

url = "https://odre.opendatasoft.com/api/explore/v2.0/catalog/datasets/eco2mix-national-tr/records"
r = requests.get(
    url,
    params={
        "limit": 1,
        "order_by": "date_heure desc",
        "where": "taux_co2 is not null",
        "select": "taux_co2",
    },
)

d = r.json()
print(d["records"][0]["record"]["fields"]["taux_co2"])
```

There's also https://www.rte-france.com/themes/swi/xml/power-co2-emission-fr.xml but it seems less public.

I wanted to contribute an OCaml version but I can't get the current version to build. What version of cohttp-eio is necessary?

**Comment by patricoferris** [comment]
Amazing thank you! Trying to fix things in https://github.com/geocaml/carbon-intensity/pull/7

**Comment by patricoferris** [comment]
Should be fixed in `main` now
